### PR TITLE
ability to filter on several tags

### LINKED ISSUE #3: filtering against multiple tags
Hello,

I need to be able to use `--volumes-by-tags` and `--instances-by-tags` with multiple tags

### PR DESCRIPTION
**Pull request by wibru**
closes #3

### CODE REVIEW

**Comment by outscale-rjt** [comment]
Hello, sorry for the late answer,

i would prefer a method where you use nargs="+" in argparse, so we can use --instances-by-tags multiple time, instead of adding complexity in parsing the input

**Comment by outscale-rjt** [comment]
thx, can you also please change the help message for the two options to specify we can use the arg multiple times
after that we're good to go

**Comment by wibru** [comment]
Sure, I didn't think about it because argparse already shows a little hint when nargs is used.

**Comment by outscale-rjt** [comment]
i have a bit of work on my side to fix the unit tests, i will bump the version after that

**Pull request merged**
